server:
  port: 8501

spring:
  data:
    cassandra:
      contact-points: localhost
      keyspace-name: accountservice
      username: root
      password: root
      port: 9042
      schema-action: create_if_not_exists
      local-datacenter: datacenter1

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
